//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPSoftworks.CodeTools.Analyzers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JPSoftworks.CodeTools.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Guid should be constructed either by parametric constructor or Guid.Empty constant or factory method Guid.NewGuid() to remove ambiguity of intend..
        /// </summary>
        internal static string AnalyzerDescription {
            get {
                return ResourceManager.GetString("AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default constructor for System.Guid should not be used.
        /// </summary>
        internal static string AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default constructor for System.Guid should not be used.
        /// </summary>
        internal static string AnalyzerTitle {
            get {
                return ResourceManager.GetString("AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inheriting from the base class expect the type name to end with allowed suffix..
        /// </summary>
        internal static string EnforcedSuffixAnalyzer_Description {
            get {
                return ResourceManager.GetString("EnforcedSuffixAnalyzer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class &apos;{0}&apos; should have one of these suffixes: &apos;{1}&apos; because it inherits from the &apos;{3}.
        ///Expected type names are: {2}.
        /// </summary>
        internal static string EnforcedSuffixAnalyzer_MessageFormat {
            get {
                return ResourceManager.GetString("EnforcedSuffixAnalyzer_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class should have a suffix.
        /// </summary>
        internal static string EnforcedSuffixAnalyzer_Title {
            get {
                return ResourceManager.GetString("EnforcedSuffixAnalyzer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use EventArgs.Empty.
        /// </summary>
        internal static string EventArgsAnalyzerDescription {
            get {
                return ResourceManager.GetString("EventArgsAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use EventArgs.Empty.
        /// </summary>
        internal static string EventArgsAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("EventArgsAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use EventArgs.Empty.
        /// </summary>
        internal static string EventArgsAnalyzerTitle {
            get {
                return ResourceManager.GetString("EventArgsAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class should have an Empty or Null static member to implement the Null Object Pattern..
        /// </summary>
        internal static string GeneralizedEmptyOrNullAnalyzer_Description {
            get {
                return ResourceManager.GetString("GeneralizedEmptyOrNullAnalyzer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class {0} should have an Empty or Null static member.
        /// </summary>
        internal static string GeneralizedEmptyOrNullAnalyzer_MessageFormat {
            get {
                return ResourceManager.GetString("GeneralizedEmptyOrNullAnalyzer_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an Empty or Null static member.
        /// </summary>
        internal static string GeneralizedEmptyOrNullAnalyzer_Title {
            get {
                return ResourceManager.GetString("GeneralizedEmptyOrNullAnalyzer_Title", resourceCulture);
            }
        }
    }
}
